# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/user/mors_ws/src/mors_hardware/power_bridge/cyphal-types/voltbro/battery/buttons.1.0.dsdl
#
# Generated at:  2024-04-08 11:06:00.261833 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.battery.buttons
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class buttons_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 emergency_button: None | uavcan.primitive.scalar.Bit_1_0 = None,
                 user_button:      None | uavcan.primitive.scalar.Bit_1_0 = None) -> None:
        """
        voltbro.battery.buttons.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param emergency_button: uavcan.primitive.scalar.Bit.1.0 emergency_button
        :param user_button:      uavcan.primitive.scalar.Bit.1.0 user_button
        """
        self._emergency_button: uavcan.primitive.scalar.Bit_1_0
        self._user_button:      uavcan.primitive.scalar.Bit_1_0

        if emergency_button is None:
            self.emergency_button = uavcan.primitive.scalar.Bit_1_0()
        elif isinstance(emergency_button, uavcan.primitive.scalar.Bit_1_0):
            self.emergency_button = emergency_button
        else:
            raise ValueError(f'emergency_button: expected uavcan.primitive.scalar.Bit_1_0 '
                             f'got {type(emergency_button).__name__}')

        if user_button is None:
            self.user_button = uavcan.primitive.scalar.Bit_1_0()
        elif isinstance(user_button, uavcan.primitive.scalar.Bit_1_0):
            self.user_button = user_button
        else:
            raise ValueError(f'user_button: expected uavcan.primitive.scalar.Bit_1_0 '
                             f'got {type(user_button).__name__}')

    @property
    def emergency_button(self) -> uavcan.primitive.scalar.Bit_1_0:
        """
        uavcan.primitive.scalar.Bit.1.0 emergency_button
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._emergency_button

    @emergency_button.setter
    def emergency_button(self, x: uavcan.primitive.scalar.Bit_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Bit_1_0):
            self._emergency_button = x
        else:
            raise ValueError(f'emergency_button: expected uavcan.primitive.scalar.Bit_1_0 got {type(x).__name__}')

    @property
    def user_button(self) -> uavcan.primitive.scalar.Bit_1_0:
        """
        uavcan.primitive.scalar.Bit.1.0 user_button
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._user_button

    @user_button.setter
    def user_button(self, x: uavcan.primitive.scalar.Bit_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Bit_1_0):
            self._user_button = x
        else:
            raise ValueError(f'user_button: expected uavcan.primitive.scalar.Bit_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.emergency_button._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.user_button._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 16, \
            'Bad serialization of voltbro.battery.buttons.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> buttons_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "emergency_button"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.primitive.scalar.Bit_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "user_button"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.primitive.scalar.Bit_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = buttons_1_0(
            emergency_button=_f0_,
            user_button=_f1_)
        _des_.pad_to_alignment(8)
        assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 16, \
            'Bad deserialization of voltbro.battery.buttons.1.0'
        assert isinstance(self, buttons_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'emergency_button=%s' % self.emergency_button,
            'user_button=%s' % self.user_button,
        ])
        return f'voltbro.battery.buttons.1.0({_o_0_})'

    _EXTENT_BYTES_ = 2

    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8n9mbt0{?YXZEF-U5Wd=8@A{@!S{1CIpQKf~_5I~*3kAKtX+=aWG1-kbf$U~Uve!GIU_U4n0t$`)*U9bmuC49Ca+8_K<eBH0'
        '<j2_GkJU===kDa)#3V8zhHF8k_)eMR5s6irD<drTZf4i&BDRI*@4Gqo$A0P1ANWOAB^gaIezUElWm-jyTFZ4eVuiITGv3unn`<Lf'
        '=Aq(hANuyOZ;mu8zx<(hQv|nYfg8B-dsy=lG=nVfs_TNwWQbytB-B!312ni&I-%+o3fhio7Uf!`!iqMJOiU%!(W<Z>YA|tv0jBpn'
        'H2VAIE(0(qgP2#9lALB|$(SNcSR#4WvVi>|te6^0Qk5XA+wR8BNrA8}TEp082q71hpZ=Y9^Tb%1B~&M;3mp{<d#SdmEb!zplBn3b'
        'iZ2*-bEl{ytXpbv;9(JN8AOxtT=SS(p7<kom3$K&o{(H=OGM(g+$=Gw&@sn=<RqtfmaBz7DVTQ?J1Bi;CwPysw~-Y*8&uGGtUz8c'
        'HC5V>eUy0AXoNJ=TLYrsryA3ybG6SkVOk_DT-JF92P31>yM?@9Qp7~_Rv`ntp?p|vyi^SloFaU@R1T}6cG08gVH6bdHqbVQhZ@AM'
        'd1ixTZ4q;S1WRxq*<un)-a8R=NGm4V^XszuMsK}~%f7H~l&IXhyO$L)-IOWp2a#;@RN=T-9P#a(YigAqj>kBOLEzZJ8+UDoCW**e'
        '|0Th8h;9`Uo9&*DVuf-Fe*4Ad$RES-a^+<q->er5+f7A=W-w?c7_~5cNOIUcNq8rxS?~UB70j^SU^RHkb&F?lmy~zb2j(y|xDPOo'
        'X;VS;vl$#7g!osOg&1f7%SRAx!3sQHgeUM6p22f?0WaZ|n~u9VP`TU}xYmCw(CWVy-ZlE~#aU@#wI?I2!Fmr2yoQYdPj3g-#wqTu'
        'uc<7Ie0HG-ZlcrxM<qNp7gpPZPk~JM+^oYF{Pyr%f_%XyH^JLLZ)4~^Nj~ci<VODh*YF#VV+8;J'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
