# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/user/mors_ws/src/mors_hardware/power_bridge/cyphal-types/voltbro/echo/echo_service.1.0.dsdl
#
# Generated at:  2024-04-08 11:06:00.244336 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.echo.echo_service
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class echo_service_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     ping: None | uavcan.primitive.String_1_0 = None) -> None:
            """
            voltbro.echo.echo_service.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param ping: uavcan.primitive.String.1.0 ping
            """
            self._ping: uavcan.primitive.String_1_0

            if ping is None:
                self.ping = uavcan.primitive.String_1_0()
            elif isinstance(ping, uavcan.primitive.String_1_0):
                self.ping = ping
            else:
                raise ValueError(f'ping: expected uavcan.primitive.String_1_0 '
                                 f'got {type(ping).__name__}')

        @property
        def ping(self) -> uavcan.primitive.String_1_0:
            """
            uavcan.primitive.String.1.0 ping
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._ping

        @ping.setter
        def ping(self, x: uavcan.primitive.String_1_0) -> None:
            if isinstance(x, uavcan.primitive.String_1_0):
                self._ping = x
            else:
                raise ValueError(f'ping: expected uavcan.primitive.String_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Issue110_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.ping._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 2064, \
                'Bad serialization of voltbro.echo.echo_service.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Issue110_) -> echo_service_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "ping"
            _des_.pad_to_alignment(8)
            _f0_ = uavcan.primitive.String_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = echo_service_1_0.Request(
                ping=_f0_)
            _des_.pad_to_alignment(8)
            assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 2064, \
                'Bad deserialization of voltbro.echo.echo_service.Request.1.0'
            assert isinstance(self, echo_service_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'ping=%s' % self.ping,
            ])
            return f'voltbro.echo.echo_service.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 258

        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8n9mbt0{`t=OKcn073KVCTej)HVkhy~actVLX*zLY#g0>@0Rj~_$0h6}RTsf%NRIU;p-6USXj26YD2o<yF+d0K6cCV&mRf45'
            'rIuQ1sa@5gE!4l3S`=vSkd$P`mj53#krpE7-QT(AT}V3O9aDd|axB&Q3J=#u%YM0%vwX*M?TY(LyI65@R;e~pula7^#Nqa9f!8Pn'
            '4bS;(wC==r;*;ORx8iK5Syg+4?MH6ZDnZe!<(!gee@k-Ra7#|^s`HD6;|Fn=wr)6{@7AiZNQK51o%eTQk|_1-_?tM~X4ygDxy44{'
            '`0<zVMzGeL;!yj<bt>g`I9si<9oSZoU=(uuP-x+ShJB-CS95jG9dQHqhLhuV-0E;F46$Xkyy*Ed7MV`Wp778H#XZj+jl%<9*nG+-'
            'pE}jyKzx*(b~Cfxaw^V<Qw`c^Hfm-KQXKC2yz0BdRj2%uYTyhzUU$B2R?!WtN~>H<X>PS-`++r5D|4$y!~KQTL`higW40kNF}<l@'
            '#aH8SujL1JwQPIkyAzE!is2T{RJTiRFd8Ezg}Xa8>w3a%hs$FfUQSR(WW_0xlAPj960TasiXVr^SNmJf&aDRDeU8JPAG<-DwQKy?'
            '=`U2QT0IWUjgt7IBgI<9Eip@QMrzDnz{B&?y5reF&0A+lw@Sk0i4d2<eIM7VB|C7c_jOIWPCPxQ%A=NL|D9JFm5S|+-s7oTH|$Eo'
            'iGLesDHHicak)cAKSv$7YFCGyt4`es+>Ic8ZH?H?gj<dnXq^g5lBGFWi@*`L%GZ><Y5Ao?Be~Z`#ZD5Cl=!A1k~^<T>y^h=j!5mC'
            'X=`VskQ$NRewLH>Mwg8=(j!WD;<nslBZG0#*0p#(;pc7l^`kAcHKLxjEuGZbzM&s&qn?O%bmiq!KHK@g7}`!dBFc1XM6~On-n5gi'
            'iFV&pi7kA-=aJ%R7wwK{Z`)U8druO(?~!9^5ABU;|9vsAm2C$eD;Mpf{So!9GR;_CdF*&PK)n$i+z=Ccu>H^z<)v5XU_`HW@x@lo'
            '_u3QZqeJv+M6W*(FMF}i;isxWuhHufnQPo8sE<5#MmkJpL`U0s%m?95s=x6}>d_H88qu-Uns?np!qS`1tOmV7$09oZ(3{~1lfBvZ'
            '#51i;Z_@FIva5Y|?(F0<uR$j$8_}sp?vo?f|E=eOgHF<^h)%EH?J>@oz59O8Jh!^^7M+eL_gFk|6vv!>u9)Zy<s!<j&q2053Fn@B'
            'RXR)gh~9o|MmUn=-gzPT=p4Nr(fNBP<}~NduTIUoFANL4L+2xU?}<3$XpX(`Lb1}j^j<`L-P4s%=Ii|zj)N{xUqlz5m^;qE@t0l-'
            'ZhD_CM)bkPb9kO>^d+-+`K95bOY}iRA3hbooP~4z=%w~Rm+8ZZ`tO-pzWoMEMyFY~t1a2x@<2*PN<~U%%|U6TWu#TCXh`dnK}JSK'
            'MMkGy^vdW}(W_&{AQPqxQ-!Hh7Fiit6<M9~$jiv9$m`UHJ{f%~`gH0?zl?qr{W=X`K*oTI0i6mc$S9~N=ro8y8G|YYbsEBuj3E_6'
            'Itd6FLWR(&j=GGxin>lsG-WhZG<6!on2a$MV>*pvT*kPHah)PWG9nd`P7|1rF`;5Yr%6o8m{c*T(-fv;OsSaCX&Tcqrd3SqG=mu#'
            'Gb(0un#HV)SrxN7&0$W)oQgS}<}oj0Ud6ml3s{h`pkhI%MJ&o#RI#Yj5|(5vsaVo!8Ot)3RV?eYf)yDn%qO!eA*CRtA!Q&fA*~?I'
            'Bpb*`$SBBY$QbCA(5s+VL$3i-f~mmNU>e9u$STNc$QsB?$ScTe$Q$UB(5IkJL!W_u3H=KCHS`-8kT9TNK*NB6f`o#Cf`)>DK?#Ej'
            '1~m*C7?LogU`WG|0U<#s5E_Jmx`eudx`w)eri7+~riP}0F$rS|#x#r>7?&`vU|hqvfk;B6Akq*Sn2<1`U_!%$fk_FI3MMs78kmwW'
            'rC>_Kl!0jp(+Z|FOdFVyFr#2b!;FDh39|}jHOv~AlQ5@XPQ#pmc?t6h<~7V4Sdg%wU`4@#h6MwQ5*8IKYFIR|Bw<Oxl7=M%%Mz9q'
            'ENfUcup&i`qQipyXOt0x$fU*3|8MkkI?+*^din+E=}eo4O+Eb_^fdo9-e&ii>S^;~zoVano;JJh;d`s6&Gr9*{9yES((^ISobA5f'
            'AGDrMILWR~!ls`7j-KwGm`y$XxO%$%Qzpx{%%+}x3O(Kat+c79Uxc1s|B2Yq)8bn`zFR`GZbmx2s-fkMhSphlBuY9F(Je8pzDya-'
            '@|ksXBBs^*%jiTtca-#|jQ+mL=(dJtG5yFgI{BnpXrb2rC_GfHa;+4Hskl+J!##KHZCJ(8_DaaDSo~fb^uujd*{OR@@=1I-z8&tc'
            'uDeaAY}IRCV7cY^O1R7NYYngDu%Y5ubvqDoXe2Kcw-|?83N_zt7LwCDaW<6Ba&1vdR!-E0?|AGwQuBQ4rXPoj?=ht9t!H6-<(sz0'
            'ZawwdO~<o}o?9N~$F$Q79It9u;_y(tQLMNn%X5Ysl?2}U@(5?s+dCtS;I0*oo$bAm+__vnmn<s8L9$x0hs*hl+)K7SI%_ZSZLt{s'
            '<|Fg-&pzop<5WwvvQswwR<v2WZUzh^xAmG^EjeZ&oK=hKn_j|}&zacY_D$O?k20Tb$!u+&B(cR&=J~Yg28nyM7MRsWrE-S58gZ*h'
            '8#(h+_iM*2*nY{bbTa2+ab8?#?;c$2T42~&u*+rkxMy*JtsjPIZmVUEDc$J)M~e9N%Gy|{_0~4cqWA;PgZSgE_$yUPrNk~@{OPv%'
            '^A+(I@z<>QoA|r<hxn)Xm-x3>4tq+Ybzw8^Hr+;Nfr#%l*&d3+eO*gLU4)C3@ubxKJNob1yZ?M8Gl-3G=l%!u%$3svB>(^'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     pong: None | uavcan.primitive.String_1_0 = None) -> None:
            """
            voltbro.echo.echo_service.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param pong: uavcan.primitive.String.1.0 pong
            """
            self._pong: uavcan.primitive.String_1_0

            if pong is None:
                self.pong = uavcan.primitive.String_1_0()
            elif isinstance(pong, uavcan.primitive.String_1_0):
                self.pong = pong
            else:
                raise ValueError(f'pong: expected uavcan.primitive.String_1_0 '
                                 f'got {type(pong).__name__}')

        @property
        def pong(self) -> uavcan.primitive.String_1_0:
            """
            uavcan.primitive.String.1.0 pong
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._pong

        @pong.setter
        def pong(self, x: uavcan.primitive.String_1_0) -> None:
            if isinstance(x, uavcan.primitive.String_1_0):
                self._pong = x
            else:
                raise ValueError(f'pong: expected uavcan.primitive.String_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Issue110_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.pong._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 2064, \
                'Bad serialization of voltbro.echo.echo_service.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Issue110_) -> echo_service_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f1_ holds the value of "pong"
            _des_.pad_to_alignment(8)
            _f1_ = uavcan.primitive.String_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = echo_service_1_0.Response(
                pong=_f1_)
            _des_.pad_to_alignment(8)
            assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 2064, \
                'Bad deserialization of voltbro.echo.echo_service.Response.1.0'
            assert isinstance(self, echo_service_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'pong=%s' % self.pong,
            ])
            return f'voltbro.echo.echo_service.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 258

        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8n9mbt0{`t=OKcn073KVCTej&aj+HoxCytXaiOtZ7lQ41YDh&{*xH&H2e5x*j(U6?zO+t}_nW0S;2%s!l$i)C1z*9g#Hd<<_'
            'rIuQ1sik&Ri?&ezTB<;S_6|vX7+Z<|MiXfva^C%&d)|elBi<?XxBots>3l^eyvbTns~4=m@m;&_{=%-*oq|<uPI%404V@%9_+jX`'
            's$t7_KAQBL<a+YrSIL)2KGLj)J;C;qSDN*(;x`LURdm0lxvscXr*PQ`yk;X{r>u3w@dLNnNJJ(wKIy%`o{&VDUnO59(E-a2L*K2m'
            'LMKQ*O?Jbz<&;F)`>s>3ZR6Q*)$Gu=!W5*CyN5!Hj<xJ7Rl8B}e0RbP-78Lk`*9oNi7>>z&GKU4(?sNYF@w?ZU5fj@J()zuKC$_f'
            'Pd;!O<DqyrJ?*FFpykw^38xWu(d^dD7NjH^{J0Ug;|-_wlSb%_JAQw@16IWit$L?iLRoILY6qb;(X4T+C!@#8n~Bn}!h38(YGQgb'
            'zf3MC(W6!n+Krm+*LEhFZdIavoXNARZaA4BBSnw&Y}RKfw>>UT^>}%Kaw0EYA}P%&&ZOb0RjCI_^!#Rj+u6C*@SD#`H1K0L?6USD'
            'Klb{I6szeak-1xvU~;0;th-fa3C={5*$a7ie(E{C9X9=KmUOEsT%HJVK05kdvr)A}r*Tu)wCmK<cN#oudG<eisa3Dr{^Sjwx^=~_'
            'x18iRNuF|XP!Sh;WDIlEvCDR2+_~&{PU!9i=?iPZZl~OG#7O5<P?{{u$vOm1xDCFh^i9Vv8yV@nw(548fTYwn6O-I~RXVRcwsK5r'
            '?@Ze|BZbtM^zO5qzBl@8q>&y|wimbW1{)cSi}r8D^9es6xTzoQqx~@rbZyzR*1=u<=l~7Gbf_;cpYqw^Z;hdYbSS1=uSQHqzSEly'
            '^EJ^UH&kK^pAX(rJRPA&VtTaetFnC{jXiqHu{21J#`M@tF|d_w$8IYZ9i_)&8ro!<u{?g;@pO!aVtQg%Ozgq-<9C#o9;YW_da{o%'
            'wsO9w?l>PErzc~2`djg`7yF#Js~YqaJsp#|#chiEnY+$NC&-NHWH*obZTQpb&)$=I^bDPh>C|S;9ruv3^xQqGLC?~un4bU6o8btP'
            'z1jDLds>^GqvvDFZ}!={vls7q4SIp{F}-xleR2f*zkFYC(2Mj^OsBW+_7vyL@4VkL_pL6yOs8Wi+!hZU#WAnkS4?z<3NaP8=OEvm'
            'gtPa(D!oF*m|neYMmUn=UV9+;=q$Y&)43Zb<}~LnZcfeX4-5;vM(1LB<BmAvXpVjJfnufC>5Z65{nJ%U=j*Kpj)UH$QcQ2(F?XDS'
            '<Ig`7-1HW`9n(9z&*3?)QA%g=!b8JH=jol8F5VTtoP~4z=%MyN7wBS4!#B(<-+qfFqto{6Mn`scJdlx*QIXMEb5Isp8Cew@8nQa&'
            'kdu*9k<)1iLo$X`4C&Y~$b>1wRAK6rM_xu=MP8>OiZY5SiaM20l2KAo(rFmOGKN(Q>okH986zr2bSk4PqpYH=(<nw|jH(#bX$)gB'
            '##D^yBp_r66+$Nuo(xZgr&Akk8EqA9ou)7)V@k!8PSco{F|A@+rx>w}SVgSU3}$4^sF=}d7PB&DRm|!%hdCK@D&};W$GnVr74teR'
            'U_r)$iUpk(u_$9v#iCA2Sdy`%Vo9fEEX!C{v8>YyR%EQGSkY+}t1?zqtm?FeH5qFv)^u9Ox{P%d>pE><L&gU4$?QtVD9C8Y7|2S<'
            'D#$X)267T|3UV5928JXIDHzf)WWbbQDlj#e2J#Z}3i2BA28t4j3W^$v21*i23Q8JE28JaJD;U-=Y+yvfh=LIfBL>P6$_mOF$_7Ry'
            'j4Bw_Flt~-!kB_F4Pyp`1ff7^5C%L6o&ryUXP_;it)Q);ZD2~ml!7S@QwF9bOe>hyFl``~5G#l^#0F+0%qW=AFk@g=!mNT>4YLO3'
            'B+Mz8(=caXUc$VBc@6Uh79=bvSkSOwU{S)Nf<+CB29_i&DOl35WMEmsvVvs|%LY~?tSHz}u%cnbz^a5*1*;lX4XjC6Q?RCC&A_^Z'
            'bp`7h)(vb(ajW96VE-BA#3*uE@$>&1J)KQ;)SjMx0D3yt<zY`x-v>R-e~ow9y{CHG{I1{8_d!pa{rB*_)zjwo|3H2)dOGd-6lc!&'
            '-|r7vPp6#ZHz#3FPk%#C_fO28p1xf@-Tf((XIpMhPv3=}?*3NV)6)+^PjCN3?CELoH6QPk(5#!0&2DOFxu>CZ79OdRPDOM_Osfx5'
            'Mzefo9i574_2x1<mCrpTy(go;uQIx;p;=7dvW!kYsTNwKbw3J^RIApkCQ&A7RqSYR$KHljne6U_e3^*fi6?^SfK_um-$_4-uO-)_'
            'L)K?*+o@Sz(+@4TmRyRCSV6PpR~<Ig9m}&rkwixNQg<s!w6EL@+;%xVy`JPF=@qUmn(5Ao+6o+>T_>7;U|kK8NC|v~bg=U*Y`=EZ'
            '_StQ~YhHDHtKz%0@pK8rX@`#Au<J>5+-p_pZq@Rg@m4*Bx4k^V+4Szt2qW0BqH(ypH&QrTC>GL1g(OT@D+ak-z{ve{+oQMll3Ww3'
            '(XZb%KmO?b(ix{wZPuKc8FZq}=4WQeFbexWbQ@L242834aRbv&*$Oxl``dwOo3%;i)2*7F&66~?GRZujHr+6FZ!|-*(W=+aa90y<'
            'BW<H#e&BxLm}NVt+Vx)MLL$zIH@mwBZ}%-Q94_0n8hhNZxWLwnQI^~4m=nsj`u~w4zP_|I7OK}ww`o?z?|B}?AHGaJSEWow90|l9'
            'uZcfh5`Pwd$&0^=zlpz#e~5pIe~I;IpgQRZn{jvPHhLRGe6Q*HP!b*O+al^CTx?9IrEcEQf4AQK=X04s?2fzeKVi40GXy0700'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'voltbro.echo.echo_service.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8n9mbt0{`t=OKcn073KVCS+?mow&gg9Cy8UziA~G-Dt{$G0~I&NCF~^7qV8x&PV~m1NOm}Mr~(0$MGLtYpaWzAXsM-^T574K'
        'mIAubQj4ZlTcA~cfHnnsA4z>^S&sik6LIm#_wN6^3zCPt6Z*HmKb2}dq7$|8QoU5pIdw1a-Ln5Hw@~(SPO&;xtJeL{OQOA(z2KT('
        '^gbD{dC51)nXi+tl5Dik3A|r6yn5(_@?4~%eV4<aQ4AZw4Vs2iamU!tGuNu+un<&pUQx6c8B==BU23~ZqO^0(3+jHgA{|<vbzXmy'
        'kV2{7BwuqfjvI!7UucA0J-L$Xl>UZN5*Z))Ub(cHPLES^L${N))jkwG(b0x`t>{*AwZI?qL;sqW<8u7UXd-&W{`K(U;FUxi?%4E2'
        '$9D)G1nzhe9sSJZQ$G3FtBi)?eR+B#hF;kl^C}$-cPeHhr6fA^X{GLuR=m<rE1@^)1>OGkIt4#;%B^q-rMc9i%NI0OEpe%*qa*os'
        'N75|!A<G~|3~%b!$)zNE+^L6drQ`;st&S!eg=i0Zs<}l!98Zu^qQ^Qi=W~f|2g@@ZT+UKPoD=6skv_#s(p+~6<$4mGTCZ=@JC_>X'
        'xKE<q5B#u=+GXB$>Weg|T1z5(Cnxpsu|l=%7a1jZV^u~k<mUNV%?sSH8f>CuIz{1gM~K1b@Q2k((G9)IO;u&pQZw)>+-h0YKX9>8'
        'F1x|_HcivH=9U{?^1CEUnYdmMA9TR@30ob#<W@$#OJ2<j{hd<!!Wna$5?i)F>r~{Wvot$v0XXJY_?qO4mR>rt<h?e^u5>_()J?^t'
        'cAmA?Gq<f8lioQqHqJ;RJtnigSLJJ~OGXBnF{L|pd$!5Q;=HJ5!=6ugzxSqkw1;|P>TS!?GS<Ew^=L2k#<ai7FQ4++fm_<pKH48s'
        'rV}HkgWs!72l$%kv2Br9!smx>%bpI>V=+D6*40_wD{T+owk;i^$74Ej(;QgJvZHt8iw@I~nEKX{=3I{5u{|B7zL=iaF(=kw`SH8*'
        'OULMmn4avyi>2)Esk`<^$LYzKp1x(iti?Jf?kNU6MNh|MZ(u94e&(J%(h0I-dbaJyzE%D*`g8Xs9z8?P#&mK$=9YVqC_R7QV$gGR'
        'GNx1Cdoyfdvo`CVzOS+Ac{&wScD>Hdot?SwG3Yd9V|wAX>tqYofAN9jL1*ZNn9gqA?Me2T-Fm<09#~v@k<P}HyCWRfifzt6(46QT'
        '<znjJ?1OB(6D~aPsC1tCV|wY15n)TVd-<W{M;GX&m|of5G5jTtrJb&M^`YfLFVibAy>?fau{GPi{!nwJSLwBw2D-beU-s7<4?Pch'
        'od#lh^RBUD4{ZO|BgvcIpf_WBd*?oUg<}lJUVP_~<wtMP+cCX+Px!JI_VL~$t%2U5cVimd*0X&34W^7<v*uP>w7aE&l!}y&l*ycf'
        '(nzaF>sT|8HYtOQij0noNqy*3(Wj%&#F|AmY!$W++oUYADzZAVCiSCVMZb=IlLj!LVnD}$NrM<vF{oqEq#+Ec7}7ChQXY8~c^!F^'
        'hB2&SSjVtQBN$OJqGQA)0ii<Z5GK`7Q&H1VGpUKDil&aHNfVe*F`;9^q)AMwnA9<8QjAzdtRpsQ3R5bkbWE8vjcFCrI;KsU!HkL-'
        '9Wy4)Vphehj#-oDFsEWp$DB#?m{&2cW8S0%ET~w}v0&077F8_jSTtz~ODdLhESa>7WfjXhmQ7m0ii#B-D<-XCRmG}~Rg>1Rreclp'
        'WONmzG^7lqETk2rHKZA23mF9&4H*L&3w;XuH1rwhvtTQ*HP{Ah3t0tO4Os(O3;hcEHS`<kw=ke!K*NB60Ski)1~m*C7_=~?U`WG|'
        'fguZd1$hm519=O>3WhZd8yL1QqF_YBh=CCcLV?gA3<wJ~1vL#d12qdx1x*c215FDP3MMp67?`jysbEsWq=88bv4U7bY#_EUrC>_K'
        'lz}M=(+Z|FOdFWCFr#2b!;FC$3$qGlHOv~AwJ@h(PQ#pmISca&<~7V4n76Q?U_rxzfdvbT3Klgi8d$Wjq+m(Inua9<OBR+DENfUc'
        'uxw#P!HR|z11lC*6|8DlHLz-7O^F)?j|uzFDI=~RlNP`Dzv0tq$)k4p^h4m&nKll)eEI?KY5q3eM)$t*Y5V&=qaOgDw!81)2g|4J'
        '&EG(NG<;gte3Ct9yYKf$&8H<M+4WA?<<mFt>F$o%<<ob{r`zu`S(asX`Sd;T>Gr46E}woFe0uX8vBRguG#_uJ(9D~WPOo!lwZoxJ'
        'CLWSWOA_58)B2;N(M+G2M@urT-<(EE`rKjCyEOWTN~7Bxn#uHS(`flmwdjeA_Fv(V?v$#<BuXWXf*T#$GPmIr#@izyUnSxX;zT{#'
        '>y*4&;K_gDOUd<Uzw^1@^h!>x8ibBtN-jnRoqDwq6g?J{J*Vb|B8e>dRQ3x=v?pJ!`^~&O{U*sq%6X10s&eE+Z`8ejRmZA9-TAVf'
        'L|Q%Il=iju!VOAax&f>8)~a86fl~<l(kO4!UNiK9id#;i<F!Vi>=&KD8*P+jdYi)|?9FV?jBo~9Ml=qz=SFfDa{W0usE~wmwBitl'
        't8?aooc8F9y(HJgchPU(w?F;lqk(f?rC2R_CA;3TwyU4pA*Ye+x$IYpo*fErUE<g6K%!M=Ppt3OZPzZ1GoF6YZcUy@+rl{GeAf0u'
        'sa~mucBN4+pW~{={E93iXMgN};n{h&UUbVH&$&drA>MA!9=z8zz;Gb%mP)L#ZE%65A4X{|t0hh--RS-yMND7ZXbZj8nx^?q{E_=X'
        '{OPOY>K-MP5=ZLd&)3CYE{ea3zh%YW#j5y+_^0@n__z2^)LR^{377M3!)<j2i1=RR^iUEV?iwQM0$lueQii%|MOSqWys=SubJgNy'
        '=j^#78Sh%PQunsa4Ly6SsiwA#93jedj}D1rEkvp}AaX+H@)R#SgK~AR)ajMWKDq4Y<-Qlp$sOCVu8nfCTk1)(iPf11>y)%9y?RXE'
        'bWfBHHV|oPc(Um1)tpS|tXwY0<vcHqyQu$q+iC89@HQ}3-X;J5'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
