# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/user/mors_ws/src/mors_hardware/power_bridge/cyphal-types/voltbro/echo/echo_msg.1.0.dsdl
#
# Generated at:  2024-04-08 11:06:00.242103 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.echo.echo_msg
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class echo_msg_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 ping: None | uavcan.primitive.String_1_0 = None) -> None:
        """
        voltbro.echo.echo_msg.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param ping: uavcan.primitive.String.1.0 ping
        """
        self._ping: uavcan.primitive.String_1_0

        if ping is None:
            self.ping = uavcan.primitive.String_1_0()
        elif isinstance(ping, uavcan.primitive.String_1_0):
            self.ping = ping
        else:
            raise ValueError(f'ping: expected uavcan.primitive.String_1_0 '
                             f'got {type(ping).__name__}')

    @property
    def ping(self) -> uavcan.primitive.String_1_0:
        """
        uavcan.primitive.String.1.0 ping
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._ping

    @ping.setter
    def ping(self, x: uavcan.primitive.String_1_0) -> None:
        if isinstance(x, uavcan.primitive.String_1_0):
            self._ping = x
        else:
            raise ValueError(f'ping: expected uavcan.primitive.String_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.ping._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 16 <= (_ser_.current_bit_length - _base_offset_) <= 2064, \
            'Bad serialization of voltbro.echo.echo_msg.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> echo_msg_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "ping"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.primitive.String_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = echo_msg_1_0(
            ping=_f0_)
        _des_.pad_to_alignment(8)
        assert 16 <= (_des_.consumed_bit_length - _base_offset_) <= 2064, \
            'Bad deserialization of voltbro.echo.echo_msg.1.0'
        assert isinstance(self, echo_msg_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'ping=%s' % self.ping,
        ])
        return f'voltbro.echo.echo_msg.1.0({_o_0_})'

    _EXTENT_BYTES_ = 258

    _MODEL_: _pydsdl_.StructureType = _restore_constant_(
        'ABzY8n9mbt0{`t=OKcn073KVCTej)HVkhy$QEb|=X*zLY#f}}N0Rj~_$0h6}RTsf%NRIU;p-5t8Xj26YD2o<yF+d0K6cCV&mRf45'
        'rIuQ1sa@5gE!4l3S`=vSkkl`>{Qsbdv=BM({?0w`LedfMsQSCbo>c2AJX#+q`{hc`@*U5$EAB7tV#Uc>rP^@4=DUFthdZwaUZWH='
        'Jm>R~x)a}xPktNUj<ca=RqbK6AGleo1Vyiwb4sH9%^LQH;xKL9bUfd!Rb!C~jW0Xz@5Uri>eunNak#^>gTQl(jll8auj0+1tUAS^'
        '_NnVs%4-m|TV*@2tsucA<o2P^!b1)FX34JR>Yh972JTHK$1S+kp;#DV+e&%S^;Ik~otS;$kxhzwo;?zWhrYD=lutf$szZVJI62+O'
        '#!kzrIKxggXrtMznN>(}xbKUq?+#U+@=vRQGvs(1^X;&TZeUef<zh;6t0mhHtl?UjTRj#YEUY9-!g8Om4T*{AP5mmq7Ki&SKd`H1'
        '+bge6G}b7F+c;C*F1f)-jFc4a?bxgv3AY_Cdpf+Fpp3|hQzRuh#hD~rwTcx#4v(+&x0an-4Zi;zhh0B$gEni|`LWYqs93dn9GaUY'
        '@kfS>wTfF}mf#H6n7x39=Vx`tvxAzq#*%K8gv%2lE`<j^sZ~pM;8gGHnsl9bdQO!`EzAD9uQn<b+Z(yZQ@3u~m4*}lHqKHe@{8hf'
        'hm1asI&{sh4msDHx)ZpYLHfoTwwnpJ9MRu86_g}PbFvnJ!)}$YDS6ZKONT~suZ@bGBp@mAO+_SkUX|7>kF6Y$+Bwr!&qyIPBE9`A'
        'C-037HquCsDBX$Mc8`q=#zos#<N1W2cih*Hw$b*8y4tpMQfud?ezb$SBHFbfFQ4++?gz%uPTCbwrc)!LJrDJ!-F!{7_nt~@;q!fu'
        '6i<6-Z$$gszAD?hlGp=}983FXe?$lGi-E0dJM>t&=l~szsC$KJ#`4Nz$I~I|j_B~FnAn5uN1iAzy+Vg0dUXR|Y~_5fJ#judLa#>j'
        '`UCN@7yBH2sv7hfy&jRd%58%Bji=5?N6C!nSUZpTApA-7H=jv8dV`Kd)U#4^-902Mz4gp$(3{i~(ea1g3`dyk&Aum|X>EFojz^ST'
        '>9ccZC!cu@IzicpPCas;9Krr?KNlQyl1@c*dhKp|IA?bK{hoPlb?I$79Z~MFc;G0GIs05O(HY7`lwX^JY<m*UJ@=|~mhut3^Vp1V'
        'B*(q`Lh#W!dMBdu_fE`d&YfSGn)hB97J8S?NA&&^amLXcd*Ov*rT6Ilh<Z0pS3a4q4_-J9x<I`VU3_BhI0MIDdMUW+1G*T|hnvsg'
        'd9Kl$%;M#jhL0}MhY?+QDt<W&=lJNQ_CS~EN<@A4%q-u2gC(QWtlQO=>~47=B_pLGrL*RsG}1ECDwZ{*b;=+kBcmdtQ#ZP0bgSsr'
        'v22hDQ--O+)G3RsjI4^RPI=^I<W=N#>P4@NUKPDM^`TEjpNc-6`q3|=Uq!!81r%fyR1|a?z<`Va6$3gAVo=7Qib0(OgbblV=u}5t'
        'MqNc+rzV;*nkt$)jbc>BsESdY#xN#hOvRW^5h59pib$t%jLR5TF|N}DCS**gn9ykwlQJe%OzJd+DH&5LrgWOdw2WyL(>l#yM#hYa'
        '8J%V^D`Qs0tWI;7lQE}aPN#Xy%a~U&uhRk+WGtvy&}k8iG8R=V>a>I<8A~dbbXvx;jAiDN*_Dt|kkXJckd}~EkY<t%WF%x1WHe+9'
        'bW7+~(5<1{fGNRLU}`W8WF=%3WHn?B<R#=4<Td0C^h)Se(5s=>K%ay@1$`R&4D?IrSJ1Da-#|e^K|w)7!N7oo0R;mZ1`G^J7*sH*'
        'VbFk(AQT7<!a!X@T|r$#-9S@9Q$bTh)4-^NQ3azKMh%Qf7*jB&Vaz}zAyN=&hzyKN7*{Z^Vcfukgb4)`8YT=(N|;nIsbSK<l!Pe-'
        'QyQiWOiP$nFs)(Qz>I_$1v46E49rTHRWPez*1(*EIR$eX<_yeBm{+i@U|z$#fdvT*3Kldh7+93Bs9;gUqJbp|OA3}WEE!mqqDIkS'
        '!Txi~hyi5M;urrndODrxs4YGH0`zpI&BK<Sehzw?{~B+z`%Lw;`LN&7&p}U{8}H!<tEbJi|AG8y^mNj54`<G9yx$+So=!N)u1vy~'
        'p8lSm-Z(K^dirtobo-}FmTj3WJ^d7Vy8T;eOHaQDJ-zl5v7@KOcYM5FLbGm0I=!Ny<&K8dS$HH$IuX$=F|EE#8O`#Ub#x-8)%(ln'
        'L_T+v^p=eNp~~pChGsGS$TB+lq*`d9*8V6wRIPHY6o;v}QMAK->-ILR;z)Z9<aR86FAn?R4y)|cJtz4jz8v2PcUd>wrc<`+H7~H-'
        'a(p%1WBIj)S8~`;ajd!>h&VKomx^1A!)=9{?=}m`>D@RRN@uyYs3mJAYQuLtb{(#HzIDrwL&f(P($3biu)Xpv+hez`dhM3uSw+t+'
        '5AkE#X$Fp0wJULWq~0i2+>+%vLybxTZ*6&mv+3=f5k|0XMPqk+ZzOjvm(L}O3UQFER_x<)J|p*%Z4U-@(=9pi9kCGp=411V&p+)w'
        '<5WwvvQswwR<v2WVFnB%xBa?XEjeZ&oE3}fn_j|}&zacY_D$O?k1(HZ$!u+&B(cR2=J~Yg28nyM7MRsWrE-S58g{Em8#(hc_Z!D7'
        '*nY{bbTa2+ab8?#?;c#-u)wgpV3*76anIrcTd#y^ZmVUEDc#ukj}-CU)zz_3>#c2?1@Q--2l2<-@z<)9N{Kzb_|qNn=d0o`;;&ip'
        'H}QAz5Ajd&FY#}&6n2$H>cVE+ZMu!l(h%QkvN05gdsY^QHj*ut?<8gJ-_3tl-~H!nnE`B$Irl&K%9&L2Bme*'
    )
    assert isinstance(_MODEL_, _pydsdl_.StructureType)
