# AUTOGENERATED, DO NOT EDIT.
#
# Generated at:  2024-04-08 11:06:00.097720 UTC
# Namespace:     voltbro.config

# There are no data types in this namespace. There may be data types in nested namespaces.
