# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/user/mors_ws/src/mors_hardware/power_bridge/cyphal-types/voltbro/config/six_step/pid_report.1.0.dsdl
#
# Generated at:  2024-04-08 11:06:00.224189 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.config.six_step.pid_report
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class pid_report_1_0:
    """
    Generated property settings use relaxed type signatures, accepting a large variety of
    possible representations of the value, which are automatically converted to a well-defined
    internal representation. When accessing a property, this strict well-defined internal
    representation is always returned. The implicit strictification enables more precise static
    type analysis.

    The value returned by the __repr__() method may be invariant to some of the field values,
    and its format is not guaranteed to be stable. Therefore, the returned string representation
    can be used only for displaying purposes; any kind of automation build on top of that will
    be fragile and prone to mismaintenance.
    """
    def __init__(self,
                 integral_error: None | uavcan.primitive.scalar.Real64_1_0 = None,
                 signal:         None | uavcan.primitive.scalar.Real64_1_0 = None) -> None:
        """
        voltbro.config.six_step.pid_report.1.0
        Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
        :param integral_error: uavcan.primitive.scalar.Real64.1.0 integral_error
        :param signal:         uavcan.primitive.scalar.Real64.1.0 signal
        """
        self._integral_error: uavcan.primitive.scalar.Real64_1_0
        self._signal:         uavcan.primitive.scalar.Real64_1_0

        if integral_error is None:
            self.integral_error = uavcan.primitive.scalar.Real64_1_0()
        elif isinstance(integral_error, uavcan.primitive.scalar.Real64_1_0):
            self.integral_error = integral_error
        else:
            raise ValueError(f'integral_error: expected uavcan.primitive.scalar.Real64_1_0 '
                             f'got {type(integral_error).__name__}')

        if signal is None:
            self.signal = uavcan.primitive.scalar.Real64_1_0()
        elif isinstance(signal, uavcan.primitive.scalar.Real64_1_0):
            self.signal = signal
        else:
            raise ValueError(f'signal: expected uavcan.primitive.scalar.Real64_1_0 '
                             f'got {type(signal).__name__}')

    @property
    def integral_error(self) -> uavcan.primitive.scalar.Real64_1_0:
        """
        uavcan.primitive.scalar.Real64.1.0 integral_error
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._integral_error

    @integral_error.setter
    def integral_error(self, x: uavcan.primitive.scalar.Real64_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real64_1_0):
            self._integral_error = x
        else:
            raise ValueError(f'integral_error: expected uavcan.primitive.scalar.Real64_1_0 got {type(x).__name__}')

    @property
    def signal(self) -> uavcan.primitive.scalar.Real64_1_0:
        """
        uavcan.primitive.scalar.Real64.1.0 signal
        The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
        """
        return self._signal

    @signal.setter
    def signal(self, x: uavcan.primitive.scalar.Real64_1_0) -> None:
        if isinstance(x, uavcan.primitive.scalar.Real64_1_0):
            self._signal = x
        else:
            raise ValueError(f'signal: expected uavcan.primitive.scalar.Real64_1_0 got {type(x).__name__}')

    # noinspection PyProtectedMember
    def _serialize_(self, _ser_: _Issue110_) -> None:
        assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
        _base_offset_ = _ser_.current_bit_length
        _ser_.pad_to_alignment(8)
        self.integral_error._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        self.signal._serialize_(_ser_)
        assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
        _ser_.pad_to_alignment(8)
        assert 128 <= (_ser_.current_bit_length - _base_offset_) <= 128, \
            'Bad serialization of voltbro.config.six_step.pid_report.1.0'

    # noinspection PyProtectedMember
    @staticmethod
    def _deserialize_(_des_: _Issue110_) -> pid_report_1_0:
        assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
        _base_offset_ = _des_.consumed_bit_length
        # Temporary _f0_ holds the value of "integral_error"
        _des_.pad_to_alignment(8)
        _f0_ = uavcan.primitive.scalar.Real64_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        # Temporary _f1_ holds the value of "signal"
        _des_.pad_to_alignment(8)
        _f1_ = uavcan.primitive.scalar.Real64_1_0._deserialize_(_des_)
        assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
        self = pid_report_1_0(
            integral_error=_f0_,
            signal=_f1_)
        _des_.pad_to_alignment(8)
        assert 128 <= (_des_.consumed_bit_length - _base_offset_) <= 128, \
            'Bad deserialization of voltbro.config.six_step.pid_report.1.0'
        assert isinstance(self, pid_report_1_0)
        return self

    def __repr__(self) -> str:
        _o_0_ = ', '.join([
            'integral_error=%s' % self.integral_error,
            'signal=%s' % self.signal,
        ])
        return f'voltbro.config.six_step.pid_report.1.0({_o_0_})'

    _EXTENT_BYTES_ = 16

    _MODEL_: _pydsdl_.DelimitedType = _restore_constant_(
        'ABzY8n9mbt0{@Lw>u=md5WlExlBRE!77!A>@}Z=qJ^WgGT_gy7N$6-AB~WM~SZjNGv*5F>_4;~;R4GL&G?FDMb@|Sp%IrChOWR1C'
        'bn@=Z>^y$^o7t_S|NOPsnf{tf<s_}rtQS>W3YLlAS)B1+loZ3VsD$FWIdz9;Vu;K1yGhCQYkl>(ex{e3`AFnBml`_FsSPFTMAecX'
        'G&vUKY=|yC85Nm|WzkED{D~O!Dlv{K#minP(n#{MkV-d;(TK}R6uI%Z@Nj4STKDJroj>(+-JFP+Qc}dV;+5V+_lM-ZXQi8C_XN+<'
        '{e+gHlqnV|lO-&)LRe}(uGuJId9ReFP%+}YDq$Iuy>-qq-_vjsPVc4x=QcH5*g5*aVL9x1(#`RES;5pnU`|A_P*KM7fdbuM!MqYy'
        'sc2ZFnAhdz;@a+UbF6n8b@z=5!RWlu>$-Ul;bVEqWIF5UCHfh%K`vCCn!ryaOB8}wA-MN;*68C$GS}(YK^XX<Yr7ux9oHs-MQx8b'
        'f#<k^YX_F+5<dv36<GKs4xyeGhCT^tXa`>4Q_Gxjd@G=q<xt|%z_$nu38B901inuLY6mv)EYC<?VtX!iJRjYAu4B87Picr-o1!uG'
        'Fa-WBm$(73{gC<=Mzbvv_=MOFb*#X5JmQ6x6<RJ0T?Y?)R)E1Mv8abet{b9n6U}v8AFUk62|a52gj$r4(8Z{Zi`8O@SUPol$MS5?'
        '3$S=h*2QcCn_8hAI$=nu?GOudw;bQ5p6z%P{rXfJ@aq^Eb8N)28ZkZ^rA49}>+Trg%_dzWv*Z=em7zgb<cbfF$Tzz`-Egj5BkuL?'
        'XVdQ{dST7^8A3<#q-~aG8a%jEAw^Q-D`D7pdb>FtJrQG`My6LHk?PgvTvQdcOgJhs9+eCU&@7lwCStt&HEiGUnvuRn!p(h-xk6!@'
        '@o0@yMblv+tLQ0m<47g3gj3T!Af=u%iDoCu;whI=EJZrN?IIs5E_0UY=A*KXGm&894(iOLx8GFgZNBX#%wVPm=G%VK&6&2NdUnt1'
        'nZD7=(D^*Zt*``%z?nuGiG=HIAWg?09B1hE%5I<S^BpbKn|sXrmQdeL_Zzs~>A2=dRFt~u9_FN)4C4Z8!c^|_VS!z2dgVdMB~yi*'
        'op}ie94PQZb7qaDsmKR!8Nts+yIN;h@Z?P`dT5#Rw_fhAysBaxdu8iL_ZRCJ%N>f`j09Y;u~{sbv4B9E(@PN_mn@%7#??Bm;wc$V'
        'PkAO;7I7&t77%!VioGEPAEMEGB?jjDS|x|TsD^M6O2}&nx8de0d;woB!&k5ZU&Af94R_#fb26Efz_J@Vx4W=2$+3`jmLoHEr#XVR'
        'KhF=|FsyEyxUdEr)1=@bJlaF+m%Y`a83ZrfE^<Tu{GC_P9B*#|8DpM;cY1pa0|O~Qe+2~of5o^Nq6Uw7Wu#ju-P)J#8Xpw55W@+4'
        '0?wMzzl@0G{}(-wP=SIPMl&Gbg_>T<mF{mf7qQFR*HuQqS&E<bak|``|2{WY#?x=wDRSTifh+wkd<s|lb7myL^_Q6CJHh><6}>Q-'
        '$L*RM?sbuS2k?G>o#g|*&P%SuVdVd<<>XmBFzaja)f6S@cXpxcFB*C0RW-%1g}aN&f8SP`qrLwCMFk_Kk_Z3*'
    )
    assert isinstance(_MODEL_, _pydsdl_.DelimitedType)
