# AUTOGENERATED, DO NOT EDIT.
#
# Source file:
# /home/user/mors_ws/src/mors_hardware/power_bridge/cyphal-types/voltbro/hmi/beeper_service.1.0.dsdl
#
# Generated at:  2024-04-08 11:06:00.249618 UTC
# Is deprecated: no
# Fixed port ID: None
# Full name:     voltbro.hmi.beeper_service
# Version:       1.0
#
# pylint: skip-file
# mypy: warn_unused_ignores=False

from __future__ import annotations

from typing import Any as _Issue110_
import numpy as _np_
from numpy.typing import NDArray as _NDArray_
import pydsdl as _pydsdl_
import uavcan.primitive.scalar
import uavcan.si.unit.duration
import uavcan.si.unit.frequency


def _restore_constant_(encoded_string: str) -> object:
    import pickle, gzip, base64
    return pickle.loads(gzip.decompress(base64.b85decode(encoded_string)))


# noinspection PyPep8Naming, SpellCheckingInspection, DuplicatedCode
class beeper_service_1_0:
    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Request:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     duration:  None | uavcan.si.unit.duration.Scalar_1_0 = None,
                     frequency: None | uavcan.si.unit.frequency.Scalar_1_0 = None) -> None:
            """
            voltbro.hmi.beeper_service.Request.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param duration:  uavcan.si.unit.duration.Scalar.1.0 duration
            :param frequency: uavcan.si.unit.frequency.Scalar.1.0 frequency
            """
            self._duration:  uavcan.si.unit.duration.Scalar_1_0
            self._frequency: uavcan.si.unit.frequency.Scalar_1_0

            if duration is None:
                self.duration = uavcan.si.unit.duration.Scalar_1_0()
            elif isinstance(duration, uavcan.si.unit.duration.Scalar_1_0):
                self.duration = duration
            else:
                raise ValueError(f'duration: expected uavcan.si.unit.duration.Scalar_1_0 '
                                 f'got {type(duration).__name__}')

            if frequency is None:
                self.frequency = uavcan.si.unit.frequency.Scalar_1_0()
            elif isinstance(frequency, uavcan.si.unit.frequency.Scalar_1_0):
                self.frequency = frequency
            else:
                raise ValueError(f'frequency: expected uavcan.si.unit.frequency.Scalar_1_0 '
                                 f'got {type(frequency).__name__}')

        @property
        def duration(self) -> uavcan.si.unit.duration.Scalar_1_0:
            """
            uavcan.si.unit.duration.Scalar.1.0 duration
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._duration

        @duration.setter
        def duration(self, x: uavcan.si.unit.duration.Scalar_1_0) -> None:
            if isinstance(x, uavcan.si.unit.duration.Scalar_1_0):
                self._duration = x
            else:
                raise ValueError(f'duration: expected uavcan.si.unit.duration.Scalar_1_0 got {type(x).__name__}')

        @property
        def frequency(self) -> uavcan.si.unit.frequency.Scalar_1_0:
            """
            uavcan.si.unit.frequency.Scalar.1.0 frequency
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._frequency

        @frequency.setter
        def frequency(self, x: uavcan.si.unit.frequency.Scalar_1_0) -> None:
            if isinstance(x, uavcan.si.unit.frequency.Scalar_1_0):
                self._frequency = x
            else:
                raise ValueError(f'frequency: expected uavcan.si.unit.frequency.Scalar_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Issue110_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.duration._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            self.frequency._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 64 <= (_ser_.current_bit_length - _base_offset_) <= 64, \
                'Bad serialization of voltbro.hmi.beeper_service.Request.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Issue110_) -> beeper_service_1_0.Request:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f0_ holds the value of "duration"
            _des_.pad_to_alignment(8)
            _f0_ = uavcan.si.unit.duration.Scalar_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            # Temporary _f1_ holds the value of "frequency"
            _des_.pad_to_alignment(8)
            _f1_ = uavcan.si.unit.frequency.Scalar_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = beeper_service_1_0.Request(
                duration=_f0_,
                frequency=_f1_)
            _des_.pad_to_alignment(8)
            assert 64 <= (_des_.consumed_bit_length - _base_offset_) <= 64, \
                'Bad deserialization of voltbro.hmi.beeper_service.Request.1.0'
            assert isinstance(self, beeper_service_1_0.Request)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'duration=%s' % self.duration,
                'frequency=%s' % self.frequency,
            ])
            return f'voltbro.hmi.beeper_service.Request.1.0({_o_0_})'

        _EXTENT_BYTES_ = 8

        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8n9mbt0{@*<ZEqVz5O&)nPTG`Gg%=4>8~UL&LR@Xf4i2xOfgsh?O_KoPL$vJOZagd9-ClS19J^8l{QxA=N+4zVh5Qj_?Q`se'
            'S|BW)ygM^H^USl)?9X$5{<TmV{_O2+z%+{kqPY?@7SCuH^MFJ$$)pyBJ9~Z4s5~;c;`@V)yHoex3-{br>^w<ng8n-_8Jkea01^>|'
            'oM&A5WIYk_V3$A5xi-!&k{(xD$kai}mcJ|3r>=deUHa9%aP}IZ#wZcyhHH0#>1O~ti*j~;Tkx1o09_@F8cK{u371Dkn76lb+KXr!'
            'Xc6S8FagUIHCR2^i)c)hgEB0QVZic%gI9~AE3+_UN+iOF9%5M9jwLnciMd8XVMxr=t^wCxMO+cph9r_9u6OJkJLBX2Sg?h@N8W{G'
            'lzwr$&b~&pp(&$^O(#0WJPGY$2RZYF4;77k8yd;oF4maC-dk%_>#h1)V|{(C)vUK#&5c&A_F=VAYppd}jb?3qquy*Zs?OKSLnLTH'
            '^GK%5**U^w<ZKDe)UHfj2nh$H%YN?QKD?!|MaDD5BWgHvC-xO`DEgd{Oe#YJa~*q=Xql^sqa)@dqu78g`@dL(2!02()!*^fQzY!t'
            'eXI@Ai)k)LsxdT?N|Ph(?TS_i>H2UFNXZdZ7`B|rBa~UF1nc5<k@pQ(DUF?dJIljZL`3m!9(#BbQDC-(krtf2tc5RzY~ty$BAmT3'
            '(nL@Ts)4_GXZ(e%U}cR>D4v?JwA~3*p@x)&G3LEH7RuzpFwk7wBk%{pd^6nd;kJ;By+UN>?CPu}dXR(?n?fXycp_1T9_?csG-{-p'
            '2ycNzAaEjJ*WTEnjES`Sk0AKodpmiIZ4NGaF+-2WId{LiN_+JW9pc<(qeQN~n1|SIB2uquT+qH>l)bKzX@B}E;r)!J!_n^Kp$>=g'
            'n$YVRL(|!OO%3Vo3qyLS{L7I>gMXh=xK*s)ZLh)|xC{4=p#ty!k3pCRuFSInCWShxy$??{G)|z|fpyrZz(?>gd;*`sXYe^}!WZxW'
            'w%|+n%8z3K*umFcH1KdJ5NJbZ2oIjX{@D%uaJD)aIe#1z4x#56B5Z}>$I;iFP&r*?2$Fk{6#%#izk$eSBDKrWAOjkIP|QKOc(YM@'
            '_-Z@*=7o3roc`hA@qcM$e@bAlZ^_g@4(UskYL`Yr#d-2i{Y$fbJA(=MiED4&MC<0nIu1T>_Ou0m1M*zao9+ex00'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    # noinspection PyUnresolvedReferences, PyPep8, PyPep8Naming, SpellCheckingInspection, DuplicatedCode
    class Response:
        """
        Generated property settings use relaxed type signatures, accepting a large variety of
        possible representations of the value, which are automatically converted to a well-defined
        internal representation. When accessing a property, this strict well-defined internal
        representation is always returned. The implicit strictification enables more precise static
        type analysis.

        The value returned by the __repr__() method may be invariant to some of the field values,
        and its format is not guaranteed to be stable. Therefore, the returned string representation
        can be used only for displaying purposes; any kind of automation build on top of that will
        be fragile and prone to mismaintenance.
        """
        def __init__(self,
                     accepted: None | uavcan.primitive.scalar.Bit_1_0 = None) -> None:
            """
            voltbro.hmi.beeper_service.Response.1.0
            Raises ValueError if any of the primitive values are outside the permitted range, regardless of the cast mode.
            :param accepted: uavcan.primitive.scalar.Bit.1.0 accepted
            """
            self._accepted: uavcan.primitive.scalar.Bit_1_0

            if accepted is None:
                self.accepted = uavcan.primitive.scalar.Bit_1_0()
            elif isinstance(accepted, uavcan.primitive.scalar.Bit_1_0):
                self.accepted = accepted
            else:
                raise ValueError(f'accepted: expected uavcan.primitive.scalar.Bit_1_0 '
                                 f'got {type(accepted).__name__}')

        @property
        def accepted(self) -> uavcan.primitive.scalar.Bit_1_0:
            """
            uavcan.primitive.scalar.Bit.1.0 accepted
            The setter raises ValueError if the supplied value exceeds the valid range or otherwise inapplicable.
            """
            return self._accepted

        @accepted.setter
        def accepted(self, x: uavcan.primitive.scalar.Bit_1_0) -> None:
            if isinstance(x, uavcan.primitive.scalar.Bit_1_0):
                self._accepted = x
            else:
                raise ValueError(f'accepted: expected uavcan.primitive.scalar.Bit_1_0 got {type(x).__name__}')

        # noinspection PyProtectedMember
        def _serialize_(self, _ser_: _Issue110_) -> None:
            assert _ser_.current_bit_length % 8 == 0, 'Serializer is not aligned'
            _base_offset_ = _ser_.current_bit_length
            _ser_.pad_to_alignment(8)
            self.accepted._serialize_(_ser_)
            assert _ser_.current_bit_length % 8 == 0, 'Nested object alignment error'
            _ser_.pad_to_alignment(8)
            assert 8 <= (_ser_.current_bit_length - _base_offset_) <= 8, \
                'Bad serialization of voltbro.hmi.beeper_service.Response.1.0'

        # noinspection PyProtectedMember
        @staticmethod
        def _deserialize_(_des_: _Issue110_) -> beeper_service_1_0.Response:
            assert _des_.consumed_bit_length % 8 == 0, 'Deserializer is not aligned'
            _base_offset_ = _des_.consumed_bit_length
            # Temporary _f2_ holds the value of "accepted"
            _des_.pad_to_alignment(8)
            _f2_ = uavcan.primitive.scalar.Bit_1_0._deserialize_(_des_)
            assert _des_.consumed_bit_length % 8 == 0, 'Nested object alignment error'
            self = beeper_service_1_0.Response(
                accepted=_f2_)
            _des_.pad_to_alignment(8)
            assert 8 <= (_des_.consumed_bit_length - _base_offset_) <= 8, \
                'Bad deserialization of voltbro.hmi.beeper_service.Response.1.0'
            assert isinstance(self, beeper_service_1_0.Response)
            return self

        def __repr__(self) -> str:
            _o_0_ = ', '.join([
                'accepted=%s' % self.accepted,
            ])
            return f'voltbro.hmi.beeper_service.Response.1.0({_o_0_})'

        _EXTENT_BYTES_ = 1

        _MODEL_: _pydsdl_.StructureType = _restore_constant_(
            'ABzY8n9mbt0{?YXYikrS6y4h0?)IgYih>ms1lcN``hI+Ep`hDtYb$<GOH5|s-auwDB$@55P_Q2q7Xk{6|HdEZ&A$4O4h)mby*WAe'
            'o|Akl|M^=k^&fXT?<OXZ5iwi~D#cgIB#%g}(p(u~xp(t>Ru{1?G=JC4xj**HNB+>)U4>*c#rWN}l9p)|K`J7~dCqkJYm1miyWHd|'
            'GniE)ZLW<_nTL|Az8{W{ePg0g`r(hfn<dm*Em&c>@%#QFV&f$5DjR~!<b==+NvNg729|JX@DnO-si5tcW>Kz1Dy(Sp$i!4q9jyuL'
            'p$gL@3NW|t;p%YR;zb0;Fi3e#DamPewlA}U2}>l;S{AT8q!m+RNvaa0b<17f83BZ4(K^PqLI_(?`tEnVyGD$qSweMk8mLz=tfkVX'
            'vcR3oBvG+<C0{V=7Eg7Ku<k&XLl1ShX^>6AbIoIFdE$HSGWjApJR!N#mWaeR-2ySH&@sn=<RquKm#c=46wJHn9dtowC;UCe+9p<U'
            'Z%{$@a)Eup)KqCh4vcq`MkA&9{v43~0o9l`m#YIb1k)mE1sm{=<vOF%yQREfQp7~_Rv`nu6ZsHrYM>f2IMwi}fpUn7+C`6|hfz?-'
            '+t9W}+|(d{%`-dlpYOpk+{bP)iIDe3f}XS$6Ycr=0DZGR-^1xpST{*j?%kb>KukAf3hO~8TRc^07mE(x#?wHp(kJ$qA~6WGExd78'
            'c4(4_to2_KY=>yGkXUT@d=wD|F8Jl^jfvle;n~UuK)z8c7?zug42NMrJ7G`_?!zXB)iZ>5a+>vzU$bC_^^H}dam@4Jk<c-86+A!('
            'eTD@CD?NysunLds@C2U1Gk6X!;3d3rb8$BZDp!VzRfqQgb_#C-?{1vC3(m*|Yd^zAunrsjqTn@bj%$BA9&N#gP!fD>)Zi1o`<O|F'
            'tfPNUpGHT=1ONa'
        )
        assert isinstance(_MODEL_, _pydsdl_.StructureType)

    def __repr__(self) -> str:
        return 'voltbro.hmi.beeper_service.1.0()'


    _MODEL_: _pydsdl_.ServiceType = _restore_constant_(
        'ABzY8n9mbt0{@+sOK%)S5XWs|d)KdoC?p^vVTVYG5oGXV?W{opV}p5YVp}l^3L><6X4+eg=0$hU+8fCdkpS6Jiv*=PbLYU36IYIW'
        '0R-Z!P`xv|J6>m<1WT5C`ceI_s$W(6o1ve69vx`?=&7XXOFwXkWP;Ox-=l889OA`c5=*X_(c{}pG`Pn;Z6?e-GOyh?`({Q@62ZPs'
        'nN&pCc^J@>+e)OKN=47kVG_|0?Y!EE1Lca?fsi{cV+j-XQfu0|mDw`7Od3o`9!J(<>2^MTWNL%8f$z<IR70pzg1f0=(%eP!eH`fQ'
        'GJ1HOv%v2P8Y4bcG}m3qCSgp!lG27pBS&&4jkt3BR8WPtJKG)&s4y@Ar`s~%>|F!r^P?~I(~t-ra>W~{VRSu+sX7{%apH1C0v6R3'
        'nA$Yz@+ihLjD6H~NnhA%AGgPxHC(%CmoOLu-<exRzd)p-kxzwRG<1M=LRv=;Qr}*@BdBNHkQm(ce2g~q)rHFJe06@Ivb3~NU7W90'
        '7niGZbJu4pbJc}PwX!(3v^>99smvOCSL$MbMkMp%$Txb3__1g708UeVu8<JoHnU{!8>qmPL>GOQ2<B16d~>KzlO4Xte3HaM5$>A}'
        'eU`{L6&}NdfRTiv1G;4Y1l&dOTgc$vmYscs0ULZ1?}pgIG?ZefacdY0Np{h<Q&OO$$<{YuNOq~fZ4*hni<r5B`*r**vpvN`L<6HQ'
        'CaD{64=JvvftA;V0<Dc?EExTq<n}U*CZ28+Vf2}d31`lkb!_I1vI#kdH%oLvut>GhHixhXOBgaYK)YAkpmY<48&&T&3SZ^wM(cYU'
        'KXYXCDH10}Pxmt-o1q({Q>f%73uDC4s@=pwqbe3%@J5IS94i7o(`UA*@AIgBY!iH8S2xlC-E8)*qJ;(xQf3~QncDP2>0;d`nITgv'
        'r!Kl1^2joc1G;AiCCfEN+MXUGY%ifvtF$*#SGp~{y5Y4E!>LYv6^eAKr$~2NT`2OJPp(q9oR6;5rr|2Q4sRU5HJJS$g)j_EsC&6g'
        '3fGbLeP~EnK7_Y6;B9zk2Hu4gcn?-#4c><jU>!b$kKkkY#Fk?&*uV`74Q#dmfi2i>$%ET)r;~v%J0mw+WbJ@M-NqRJUE%oq6|M!{'
        'P!?}#iDXvf41{n2G(>4%rFz0^CP0I0c^#DUo{i{X*Eagap1ysAf7m>D8dvTV06V`HN47ack0n))W}sp{*;fBpYoGUt1boY+on67%'
        'mF{eN^U-M=Hf&CU$pjlEJN7hOKJn?w4q5V^?;);h;bP8h=Sgs6)<Lk&Ph$3x9$$^)fYIp4+kp%ZW(*%@L}uk!B=UFo?MX!H(ZUNg'
        'k_pOMPj6zMnbE-_qh$<sxtGy0^*ol?ccG~IPx$o&)jz-kcnCi}18jesEaK(<iS6WbrjU*@o+;)3_#AIjzgV|KhlgV2{SAM?zwl4`'
        'l)fEihn@cb6t5lustEu9'
    )
    assert isinstance(_MODEL_, _pydsdl_.ServiceType)
